### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by raditp** [mbockus/veracode-scanner#7]
When I’m trying to upload file using the Veracode plug-in, the following error occurred:

Connection timed out: connect
java.net.ConnectException: Connection timed out: connect
FATAL: java.net.ConnectException: Connection timed out: connect
org.jenkinsci.plugins.veracodescanner.exception.VeracodeScannerException: java.net.ConnectException: Connection timed out: connect
                at org.jenkinsci.plugins.veracodescanner.VeracodeNotifier.getAppId(VeracodeNotifier.java:230)
                at org.jenkinsci.plugins.veracodescanner.VeracodeNotifier.performScan(VeracodeNotifier.java:143)
                at org.jenkinsci.plugins.veracodescanner.VeracodeNotifier.perform(VeracodeNotifier.java:87)
                at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
                at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:781)
                at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:753)
….

Proxy is already set in Jenkins. And I'm able to login to veracode site via browser. Is there any additional setting required?

**Comment by edbrannin** [comment]
I'm getting this error too -- it's great that there's a workaround, but it would be better if the plugin could use the Jenkins-configured proxy settings.

**Comment by tpilli-zz** [comment]
I'm getting this error when I try to upload from java application. Do I need to use java API wrappers?

**Comment by msrinivascharan** [comment]
Faced same issue with Azure DevOps Veracode extension to upload and scan, fixed the issue by setting proxy to JVM via arguments (-phost xyzproxy.com -pport 1243) option in the extension. it worked for me.
