### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by maryamghani** [mbockus/veracode-scanner#8]
Veracode scan failed.
FATAL: Veracode scan failed.
org.jenkinsci.plugins.veracodescanner.exception.VeracodeScannerException: Veracode scan failed.
    at org.jenkinsci.plugins.veracodescanner.VeracodeNotifier.performScan(VeracodeNotifier.java:169)
    at org.jenkinsci.plugins.veracodescanner.VeracodeNotifier.perform(VeracodeNotifier.java:87)
    at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:736)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.cleanUp(MavenModuleSetBuild.java:1064)
    at hudson.model.Run.execute(Run.java:1778)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:234)
Caused by: java.io.FileNotFoundException: /my directory/ (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at com.veracode.util.http.ClientHttpRequest.setParameter(ClientHttpRequest.java:356)
    at com.veracode.util.http.ClientHttpRequest.setParameter(ClientHttpRequest.java:384)
    at com.veracode.util.http.ClientHttpRequest.setParameters(ClientHttpRequest.java:408)
    at com.veracode.util.http.ClientHttpRequest.post(ClientHttpRequest.java:479)
    at com.veracode.util.http.ClientHttpRequest.post(ClientHttpRequest.java:585)
    at com.veracode.util.http.WebClient.consumeResponse(WebClient.java:140)
    at com.veracode.util.http.WebClient.uploadFile(WebClient.java:35)
    at com.veracode.apiwrapper.wrappers.UploadAPIWrapper.uploadFile(UploadAPIWrapper.java:1151)
    at org.jenkinsci.plugins.veracodescanner.VeracodeNotifier.performScan(VeracodeNotifier.java:152)
    ... 9 more

**Comment by turri87** [comment]
> I'm receiving this error :
> 
> VeracodeJavaAPI v13.6.1.7
> Parsing error(s):
> -filepath is required for the selected action.
> 
> The following parameters are optional for the selected action:
> -format -inputfilepath -logfilepath -phost -ppassword
> -pport -puser
> 
> [ip 09:53:29]
> [ip 09:53:29] Upload and scan failure.
> Build step 'Upload and scan with Veracode' marked build as failure
> Finished: FAILURE
> I'm receiving this error for my path file : **/myfilename.jar

@maloochpich I'm Getting the same error. Was you able to sort it out?

**Comment by tjarrettveracode** [comment]
Suggestion @turri87  -- per @mbockus 's suggestion above, please consider trying the official Veracode plugin available for download [here](https://help.veracode.com/reader/PgbNZUD7j8aY7iG~hQZWxQ/DhfpJ3OQzjGCQ3M9mTzfhg). I don't think @mbockus is actively maintaining this plugin any more.
